openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 0.1.0
paths:
  /items:
    get:
      summary: List all items
      responses:
        '200':
          description: A JSON array of items
          content:
            application/json:
              schema: 
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
